// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: proxy/nidhogg/config.proto

package nidhogg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerAddress      string                 `protobuf:"bytes,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	ServerPort         uint32                 `protobuf:"varint,2,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	Psk                string                 `protobuf:"bytes,3,opt,name=psk,proto3" json:"psk,omitempty"`
	TunnelPath         string                 `protobuf:"bytes,4,opt,name=tunnel_path,json=tunnelPath,proto3" json:"tunnel_path,omitempty"`
	Fingerprint        string                 `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	ShapingMode        string                 `protobuf:"bytes,6,opt,name=shaping_mode,json=shapingMode,proto3" json:"shaping_mode,omitempty"`
	Insecure           bool                   `protobuf:"varint,7,opt,name=insecure,proto3" json:"insecure,omitempty"`
	ConnectionPoolSize int32                  `protobuf:"varint,8,opt,name=connection_pool_size,json=connectionPoolSize,proto3" json:"connection_pool_size,omitempty"`
	IdleTimeout        string                 `protobuf:"bytes,9,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	ConnectionMaxAge   string                 `protobuf:"bytes,10,opt,name=connection_max_age,json=connectionMaxAge,proto3" json:"connection_max_age,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_nidhogg_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_nidhogg_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_nidhogg_config_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfig) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *ClientConfig) GetServerPort() uint32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

func (x *ClientConfig) GetPsk() string {
	if x != nil {
		return x.Psk
	}
	return ""
}

func (x *ClientConfig) GetTunnelPath() string {
	if x != nil {
		return x.TunnelPath
	}
	return ""
}

func (x *ClientConfig) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *ClientConfig) GetShapingMode() string {
	if x != nil {
		return x.ShapingMode
	}
	return ""
}

func (x *ClientConfig) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *ClientConfig) GetConnectionPoolSize() int32 {
	if x != nil {
		return x.ConnectionPoolSize
	}
	return 0
}

func (x *ClientConfig) GetIdleTimeout() string {
	if x != nil {
		return x.IdleTimeout
	}
	return ""
}

func (x *ClientConfig) GetConnectionMaxAge() string {
	if x != nil {
		return x.ConnectionMaxAge
	}
	return ""
}

type ServerConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Psk                 string                 `protobuf:"bytes,1,opt,name=psk,proto3" json:"psk,omitempty"`
	ProxyTo             string                 `protobuf:"bytes,2,opt,name=proxy_to,json=proxyTo,proto3" json:"proxy_to,omitempty"`
	TunnelPath          string                 `protobuf:"bytes,3,opt,name=tunnel_path,json=tunnelPath,proto3" json:"tunnel_path,omitempty"`
	ProfileTargets      []string               `protobuf:"bytes,4,rep,name=profile_targets,json=profileTargets,proto3" json:"profile_targets,omitempty"`
	ProfileInterval     string                 `protobuf:"bytes,5,opt,name=profile_interval,json=profileInterval,proto3" json:"profile_interval,omitempty"`
	ProfileMinSnapshots int32                  `protobuf:"varint,6,opt,name=profile_min_snapshots,json=profileMinSnapshots,proto3" json:"profile_min_snapshots,omitempty"`
	TelemetryThreshold  int32                  `protobuf:"varint,7,opt,name=telemetry_threshold,json=telemetryThreshold,proto3" json:"telemetry_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_nidhogg_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_nidhogg_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_nidhogg_config_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetPsk() string {
	if x != nil {
		return x.Psk
	}
	return ""
}

func (x *ServerConfig) GetProxyTo() string {
	if x != nil {
		return x.ProxyTo
	}
	return ""
}

func (x *ServerConfig) GetTunnelPath() string {
	if x != nil {
		return x.TunnelPath
	}
	return ""
}

func (x *ServerConfig) GetProfileTargets() []string {
	if x != nil {
		return x.ProfileTargets
	}
	return nil
}

func (x *ServerConfig) GetProfileInterval() string {
	if x != nil {
		return x.ProfileInterval
	}
	return ""
}

func (x *ServerConfig) GetProfileMinSnapshots() int32 {
	if x != nil {
		return x.ProfileMinSnapshots
	}
	return 0
}

func (x *ServerConfig) GetTelemetryThreshold() int32 {
	if x != nil {
		return x.TelemetryThreshold
	}
	return 0
}

var File_proxy_nidhogg_config_proto protoreflect.FileDescriptor

const file_proxy_nidhogg_config_proto_rawDesc = "" +
	"\n" +
	"\x1aproxy/nidhogg/config.proto\x12\x12xray.proxy.nidhogg\"\xed\x02\n" +
	"\fClientConfig\x12%\n" +
	"\x0eserver_address\x18\x01 \x01(\tR\rserverAddress\x12\x1f\n" +
	"\vserver_port\x18\x02 \x01(\rR\n" +
	"serverPort\x12\x10\n" +
	"\x03psk\x18\x03 \x01(\tR\x03psk\x12\x1f\n" +
	"\vtunnel_path\x18\x04 \x01(\tR\n" +
	"tunnelPath\x12 \n" +
	"\vfingerprint\x18\x05 \x01(\tR\vfingerprint\x12!\n" +
	"\fshaping_mode\x18\x06 \x01(\tR\vshapingMode\x12\x1a\n" +
	"\binsecure\x18\a \x01(\bR\binsecure\x120\n" +
	"\x14connection_pool_size\x18\b \x01(\x05R\x12connectionPoolSize\x12!\n" +
	"\fidle_timeout\x18\t \x01(\tR\vidleTimeout\x12,\n" +
	"\x12connection_max_age\x18\n" +
	" \x01(\tR\x10connectionMaxAge\"\x95\x02\n" +
	"\fServerConfig\x12\x10\n" +
	"\x03psk\x18\x01 \x01(\tR\x03psk\x12\x19\n" +
	"\bproxy_to\x18\x02 \x01(\tR\aproxyTo\x12\x1f\n" +
	"\vtunnel_path\x18\x03 \x01(\tR\n" +
	"tunnelPath\x12'\n" +
	"\x0fprofile_targets\x18\x04 \x03(\tR\x0eprofileTargets\x12)\n" +
	"\x10profile_interval\x18\x05 \x01(\tR\x0fprofileInterval\x122\n" +
	"\x15profile_min_snapshots\x18\x06 \x01(\x05R\x13profileMinSnapshots\x12/\n" +
	"\x13telemetry_threshold\x18\a \x01(\x05R\x12telemetryThresholdB)Z'github.com/xtls/xray-core/proxy/nidhoggb\x06proto3"

var (
	file_proxy_nidhogg_config_proto_rawDescOnce sync.Once
	file_proxy_nidhogg_config_proto_rawDescData []byte
)

func file_proxy_nidhogg_config_proto_rawDescGZIP() []byte {
	file_proxy_nidhogg_config_proto_rawDescOnce.Do(func() {
		file_proxy_nidhogg_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_nidhogg_config_proto_rawDesc), len(file_proxy_nidhogg_config_proto_rawDesc)))
	})
	return file_proxy_nidhogg_config_proto_rawDescData
}

var file_proxy_nidhogg_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_nidhogg_config_proto_goTypes = []any{
	(*ClientConfig)(nil), // 0: xray.proxy.nidhogg.ClientConfig
	(*ServerConfig)(nil), // 1: xray.proxy.nidhogg.ServerConfig
}
var file_proxy_nidhogg_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_nidhogg_config_proto_init() }
func file_proxy_nidhogg_config_proto_init() {
	if File_proxy_nidhogg_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_nidhogg_config_proto_rawDesc), len(file_proxy_nidhogg_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_nidhogg_config_proto_goTypes,
		DependencyIndexes: file_proxy_nidhogg_config_proto_depIdxs,
		MessageInfos:      file_proxy_nidhogg_config_proto_msgTypes,
	}.Build()
	File_proxy_nidhogg_config_proto = out.File
	file_proxy_nidhogg_config_proto_goTypes = nil
	file_proxy_nidhogg_config_proto_depIdxs = nil
}
